spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/documentmanagementsystem
    username: docman
    password: thisisadummypassword
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
    hibernate:
      ddl-auto: update
storage:
  files:
    rootPath: /FileExplorer
flyway:
  baseline-on-migrate: true
  schemas: public
  defaultSchema: public